FROM jenkins/jenkins:lts

USER root

# Gerekli paketlerin yüklenmesi
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    lsb-release \
    software-properties-common

# Docker'ın GPG anahtarının eklenmesi
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

# Docker deposunun eklenmesi
RUN echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

# Docker CLI'nin yüklenmesi
RUN apt-get update && apt-get install -y docker-ce-cli

# Tini'nin indirilmesi ve kurulması
RUN curl -fsSL https://github.com/krallin/tini/releases/download/v0.19.0/tini-static-amd64 -o /usr/local/bin/tini \
    && chmod +x /usr/local/bin/tini

# İzinleri ayarlayın
RUN chown -R 1000:1000 /var/jenkins_home \
    && chmod -R 775 /var/jenkins_home

USER jenkins

ENTRYPOINT ["/usr/local/bin/tini", "--", "jenkins.sh"]
